@startuml
skinparam defaultFontName "Comic Sans MS"
header webrpg.pl
title "diagram komponentów"
left to right direction

interface "HTTPS/WebSocket" as HTTPS

node web_client {
    note as N1
        React i ważniejsze moduły
    end note
    [React] -(0- [characterSheet] 
    [React] -(0- [characterList]
    [characterSheet] -(0)- HTTPS
    [characterSheet] - [dice]
    [characterList] -(0)- HTTPS

}

node "server" {
    HTTPS -(0)- [Express]
    [Express-hbs] - [Express]
    [Express] - [Express-session]

    note top of [Express-hbs]
        layout manager
    end note

    note bottom of [Express]
        silnik serwera
    end note

    [Express] -(0- Controllers
    node Controllers {
        [sessionController] - [userController]
        [userController] - [gameController]
    }

}


database "MongoDB"
[gameController] -(0- MongoDB
[userController] -(0- MongoDB
' Controllers -(0- MongoDB

@enduml