@startuml
skinparam defaultFontName "Comic Sans MS"
header webrpg.pl
title "diagram sekwencji - rzut kością"

actor Player
participant "moduł\nkości" as ReactDice
participant "gameController" as GameController

Player -> ReactDice: wywołanie rzutu kością
ReactDice -> GameController: poinformowanie o\nnowym rzucie
GameController -> Player: poinformowanie wszystkich graczy\no rzucie i jego wyniku





@enduml