@startuml
skinparam defaultFontName "Comic Sans MS"
header webrpg.pl
title "diagram sekwencji - logowanie"

actor Player
participant "sessionController" as SessionController 
database MongoDB as db


Player -> SessionController : logowanie

activate SessionController
SessionController -> db : sprawdzanie poświadczeń
activate db

db --> SessionController : status
deactivate db

alt sukces
    SessionController --> Player : stworzenie sesji

else błąd
    SessionController --> Player : błąd
    deactivate SessionController
    end




@enduml