@startuml
skinparam defaultFontName "Comic Sans MS"
header webrpg.pl
title "diagram komponentów"
'left to right direction

interface HTTPS

node "web client" {
    '[View] <-- HTTPS
    [View] <-- [charSheetController] 
    [View] <-- [charListController]
    [charSheetController] --> HTTPS
    [charListController] --> HTTPS

}

node "server" {
    [userController] <--> [databaseController] 
    HTTPS <--> [userController]
    
}


database "MongoDB"
[databaseController] <-- MongoDB

@enduml