@startuml
header webrpg.pl
footer cyberpunk2077
title "diagram komponentów"
'left to right direction

interface HTTPS

node "web client" {
    [View] <-- HTTPS
    [Controller] --> HTTPS
    
    note right of [Controller]
        Wstępnie przygotowuje
        dane do przetwarzania
        i je wysyła na serwer
    end note
    note right of [View]
        Wyświetla dane
    end note


}

node "server" {
    HTTPS <--> [Model]: "comunnicates\nwith client"
    [Model] <-- [Data]
    note right of [Data]
        Zapewnia koumnikację
        w obie strony
        z bazą danych
    end note

    note right of [Model]
        Przetwarza dane
    end note
}

database "MongoDB"
[Data] <-- MongoDB: "gets from"

@enduml